### ISSUE TITLE
travis build dies due to _docs.sh 

### ISSUE THREAD

**Issue by SwartzCr** [certbot/website#113]
travis can't build the docs thanks to some letsencrypt dependency
I think travis shouldn't be testing the docs since that gets managed in the certbot/certbot repo
example: https://travis-ci.org/certbot/website/builds/132486221

**Comment by mfb** [comment]
Theoretically we do want integration testing of the docs built w/ the certbot sphinx theme to happen somewhere, sometime.

I see a new version of pkginfo just came out, maybe there is some compatibility issue? https://pypi.python.org/pypi/pkginfo

**Comment by mfb** [comment]
Found a report upstream here: https://bugs.launchpad.net/pkginfo/+bug/1585006

**Comment by SwartzCr** [comment]
yeah looks like, I guess we'll just wait for it to be resolved
