### ISSUE TITLE
Gentoo Nginx Instructions

### ISSUE THREAD

**Issue by bmw** [certbot/website#116]
With #112, the Gentoo Nginx advanced instructions are inaccurate. If the `letsencrypt-nginx` package still works or there is a `certbot-nginx` package we should still suggest it to people in advanced mode. If not, we should remove the now invalid instructions on how to install it.

**Comment by SwartzCr** [comment]
I think with the most recent changes (unpushed) we'll tell people to install the normal certbot package and then try to use the experimental nginx plugin, but with the invocation of `certbot`
so this: https://certbot.eff.org/#gentoo-nginx
but with the last line being: `$ emerge -av app-crypt/certbot`

**Comment by bmw** [comment]
Here's a screenshot based on current master. The instructions for the experimental nginx plugin tell you to do weird stuff with emerge/layman and then install app-crypt/certbot.

![screenshot from 2016-05-24 16-35-38](https://cloud.githubusercontent.com/assets/6504915/15523195/97674a1c-21cd-11e6-9afd-9c55a12b199c.png)

**Comment by SwartzCr** [comment]
yup, we should likely rip that out

**Comment by SwartzCr** [comment]
https://github.com/certbot/website/pull/117 for review
