### ISSUE TITLE
Red Hat Packaging

### ISSUE THREAD

**Issue by bmw** [certbot/website#118]
`certbot` is packaged on Fedora 23+ and in EPEL for CentOS/RHEL 7. It doesn't appear that the Apache plugin is packaged though.

**Comment by bmw** [comment]
Is this correct @hogarthj?

**Comment by hogarthj** [comment]
Yes. At the time letsencrypt was first packaged the httpd plugin basically
assumed Debian layouts so we decided to support certonly alone at the time.

It's just stayed that way for the time being with no one requesting it so
no time of its spent testing and packaging it.

I'll log a bug on bugzilla as a reminder for us to revisit this.

**Comment by hogarthj** [comment]
For anyone who wants to follow here's our bugzilla entry to track it:

https://bugzilla.redhat.com/show_bug.cgi?id=1339752

**Comment by hogarthj** [comment]
This is why I hadn't bothered with the apache plugin yet, from the system requirements:

"The Apache plugin currently requires a Debian-based OS with augeas version 1.0; this includes Ubuntu 12.04+ and Debian 7+."

Is that no longer valid? If not I'll do the requisite testing and package review request from our side

**Comment by SwartzCr** [comment]
oh weird, where is that text?
as long as you have a proper version of augeas, apache should work - there's a file that specifies which directories conf files live in, which should be updated appropriately: https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py

**Comment by hogarthj** [comment]
https://github.com/certbot/certbot/blob/master/README.rst#system-requirements

i'm doing a test build now

**Comment by hogarthj** [comment]
Package review request is up:
https://bugzilla.redhat.com/show_bug.cgi?id=1340152
