### ISSUE TITLE
Interactive plugin selection not available in Xenial

### ISSUE THREAD

**Issue by patf** [certbot/website#119]
The instructions for Xenial (for example with Nginx) mention that `letsencrypt certonly` "[...] will allow you interactively select the plugin and options used to obtain your certificate."

That feature isn't available in the version of `letsencrypt` in Xenial - the client will simply use standalone.

The Xenial instructions should probably use `--webroot` by default, while mentioning that `--standalone` is available in case anyone would rather use that for some reason.

I remember reading about plans for a certbot PPA for Xenial, so I guess if that's going to happen soon-ish, it might be easier to just replace the instructions with ones for the PPA, which would make this issue go away as well.

Related topic from the community forum: https://community.letsencrypt.org/t/letsencrypt-renew-does-not-work-ubuntu-nginx/16219

**Comment by patf** [comment]
> The Xenial instructions should probably use `--webroot` by default

To be a bit more precise, the instructions should probably include `--webroot-path` and `-d` as well, since interactive webroot isn't available in that version either.

**Comment by pde** [comment]
The problem is that the `letsencrypt` package in Xenial is old (version 0.4.2), and it only supported webroot when selected from the command line. @hlieberman what's the status of getting a recent Certbot into Xenial?  If not, we should tweak the instructions so that they're accurate on that platform...

**Comment by pde** [comment]
This issue is pretty bad, and has been lurking for way too long.  @SwartzCr, do you think you could shepherd a mitigation for it?  Probably that's updating the instruction generator, until we ask Xenial to ship 0.8.1 and they do it...
