### ISSUE TITLE
Debian Packaging

### ISSUE THREAD

**Issue by bmw** [certbot/website#120]
Certbot is in Debian testing and should be in jessie-backports soon. We should update instructions to reflect this.

**Comment by bmw** [comment]
Package has been uploaded to `jessie-backports`.

**Comment by chriscroome** [comment]
I can see [python-acme_0.6.0-1~bpo8+1_amd64.changes ACCEPTED into jessie-backports](https://lists.alioth.debian.org/pipermail/letsencrypt-devel/Week-of-Mon-20160523/thread.html#590)  but I can't see that `certbot` has been accepted into `jessie-backports`? 

It's a shame it wasn't added before `letsencrypt` was removed...

**Comment by chriscroome** [comment]
There are a couple of Debian bugs related to this issue:

* [Bug #824172](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824172)
* [Bug #825318](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825318)

And I also found [this page](https://ftp-master.debian.org/new/python-certbot_0.6.0-2~bpo8%2B1.html) which I guess is a result of the package being uploaded to `jessie-backports`? What is holding this back from reaching the mirrors, the FTP Masters or something else?

**Comment by chriscroome** [comment]
The `certbot` package is now available from `jessie-backports` and unlike the `letsencrypt` package it has a working cron job and this has the potential to cause [unexpected side effects](https://community.letsencrypt.org/t/solved-rate-limit-with-san-certificate-90-hostnames/4010/11)...

**Comment by danger89** [comment]
@chriscroome 
There is another bug related to python-psutil in Jessie:

- [Bug #825830](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825830)

This will be hopefully fixed upstream, but just that you know about the existence of it.

Thanks.
