### ISSUE TITLE
Debian cron job

### ISSUE THREAD

**Issue by bmw** [certbot/website#126]
The Debian package provides a cron job to automatically renew your certificates. Information about this should be included in the Debian instructions.

**Comment by SwartzCr** [comment]
paging @hlieberman for more info on this, if you give me some info or wording I can add it to the debian instructions

**Comment by hlieberman** [comment]
Debian versions >= 0.8 install a cron job automatically into /etc/cron.d/certbot.  This cronjob runs a renewal twice a day (0000, 1200), sleeping for a random interval between 0 and 60 minutes to smooth out the load on the boulder servers.

Version 0.6 published a buggy renew file that would do the renewal 120 times a day. Upgrading fixes the problem.

**Comment by SwartzCr** [comment]
I've added a note in #134 - feel free to review and merge @bmw or @hlieberman
