### ISSUE TITLE
Help non-sysadmins

### ISSUE THREAD

**Issue by bmw** [certbot/website#137]
As suggested by @schoen, in the instruction generator, we should provide option(s) such as "shared hosting" or "hosting company" or even "I'm not sure" or "I don't know". The reason for this is some people attempt to use Certbot with very limited access to their server. The client provides very little support for this (you have to use the manual plugin and install the certificate by hand every 3 months).

In the text for this option, we should explain the problem to the user and tell them to see if their hosting provider has integrated Let's Encrypt support. If they haven't, perhaps we should suggest they ask their hosting provider to do so. We could also potentially tell the users about the other options available to set up TLS on their site, however, since this isn't likely to be one of our products, we have little/no control over the quality, security, etc of such a product and we should be careful.

**Comment by bmw** [comment]
I have a rough plan for how I want to implement this and other drop down options such as CPanel, Windows, shared hosting, etc. I'm unsure the best way to organize this though. For example, CPanel is neither an operating system or a web server.

Furthermore, I believe all cases of the instruction generator require you to select both options for instructions to be displayed. This should probably be changed because asking you to pick an operating system after you selected shared hosting as your web server is a bit silly. With that said, having both drop downs displayed and having one have no effect also seems a bit weird.

If someone has thoughts about the best way to display these options while making minimal changes to the current website, please let me know.

**Comment by bmw** [comment]
I'm currently thinking of changing "I'm using Webserver on Operating System", where Websever and Operating System are dropdowns, to "I'm using Software on System", where Software and System are dropdowns. Things like CPanel go in software, while Windows, shared hosting, etc. go under system. Both categories will have something like an "I don't know" option and for many of these new options, selecting an item from only one dropdown is enough to generate instructions.

**Comment by pde** [comment]
I don't feel like I have any magical ability to tell whether things will make more sense to people after that change. If your intuition is that this makes more sense, go for it? The gold standard is to watch a lot of users interact with the two things, and see which one confuses them less.

**Comment by pde** [comment]
(but we'll probably not get a chance to do that soon, if ever)

**Comment by bmw** [comment]
The two things being the current instructions and what I'm proposing? I think "Webserver on Operating System" is much more clear, however, it doesn't really allow us to provide instructions for things like shared hosting and CPanel which I thought you wanted us to add very soon.

**Comment by bmw** [comment]
With that said, I agree there is value in adding instructions for these cases. I'm happy to go with what I think is best, however, since you had a strong opinion about this the last time I talked to you about it, I thought I'd check before I spent time implementing something only to find out we want to go another direction.
