### ISSUE TITLE
Dockerfile for development

### ISSUE THREAD

**Issue by bmw** [certbot/website#142]
It'd be nice to have a Dockerfile for running `gulp`, tests, etc. I have a docker container locally for running `gulp`, but I haven't played around with tests or wrote it up in a Dockerfile.

**Comment by vbrown608** [comment]
@SwartzCr and I wrote a Dockerfile for this a couple weeks ago. I haven't had time to clean it up for a PR, but I can at least share what we've got so far. I'll post something tonight.

**Comment by vbrown608** [comment]
Okay, here's a first pass on a Dockerfile: 
https://github.com/certbot/website/blob/dockerize/Dockerfile
The build and tests pass for me with `gulp build && npm test`.

A couple issues:

*The tests (html-proofer) were throwing a character encoding error without that UTF-8 business. Not sure if there's a cleaner way to handle that.

*I wasn't sure what CMD would be most helpful considering some people will want to run `gulp watch` and others will want to run `gulp build` followed by `npm test`.

**Comment by bmw** [comment]
Awesome. Thanks for this @vbrown608. Both the build and tests pass for me as well.

> *The tests (html-proofer) were throwing a character encoding error without that UTF-8 business. Not sure if there's a cleaner way to handle that.

Yeah I'm also not sure the best way to handle that. This is shorter and seems to work for me, but not sure if there are any downsides.
```
# Set UTF-8 character encoding
RUN apt-get install locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL C.UTF-8
```
> *I wasn't sure what CMD would be most helpful considering some people will want to run gulp watch and others will want to run gulp build followed by npm test.

I think that's right. There's not going to be a single command people want to run, so giving them a shell and allowing them to run what they want is probably the best approach. While certainly not an ideal Dockerfile, that's what we do for [Certbot](https://github.com/certbot/certbot/blob/master/Dockerfile-dev).

**Comment by SwartzCr** [comment]
We should make sure someone has the ability to build and deploy the website while I'm gone. @vbrown608 can you still do that? Otherwise we should get max/starchy to give @bmw permission.
I've shared my dockerfile and deploy script with him - and he can test it by applying the #160 change

**Comment by bmw** [comment]
This has been resolved.
