### ISSUE TITLE
Include --agree-tos for --dry-run on Xenial

### ISSUE THREAD

**Issue by bmw** [certbot/website#159]
On Ubuntu 16.04, `letsencrypt renew --dry-run` won't work unless you also include `--agree-tos` on the command line. Additionally, user's will see:
```
2016-04-02 13:49:45,115:WARNING:letsencrypt.client:Registering without email!
```
We should tell users to add the `--agree-tos` flag when testing their renewal setup and perhaps also tell them to ignore the e-mail address warning.

**Comment by danpoltawski** [comment]
This hit me too - +1

**Comment by SwartzCr** [comment]
made a PR https://github.com/certbot/website/pull/160
