### ISSUE TITLE
RHEL 7 users need to enable the "optional" EPEL channel

### ISSUE THREAD

**Issue by pde** [certbot/website#161]
Per https://github.com/certbot/certbot/issues/3544 the instructions are currently missing this detail for RHEL 7 users (though CenOS 7 users don't need to do this).

**Comment by bmw** [comment]
Worse than that, you can do `yum install epel-release` on RHEL 7. That's a CentOS convenience.

**Comment by draker42** [comment]
bmw: I think you mean "can NOT", otherwise your meaning is reversed. 

pde: if you read hogarthj's comment carefully, you will realize that what he said referred to the **RHEL** optional channel. (There is no "optional epel channel").

**Comment by bmw** [comment]
@draker42, you're correct. Thanks for pointing that out. I updated my post.

**Comment by draker42** [comment]
Awesome. Can you teach me how to certbot? :(

**Comment by bmw** [comment]
@draker42, I'm glad you got it to work and I'm sorry I wasn't able to help you before you struggled through it.

Did you have problems other than the one(s) described in this (or other) issue(s)? If so, we'd love to know what happened so we can make it easier for people in the future.

**Comment by bmw** [comment]
Fixed in #167.

**Comment by kavikon** [comment]
@draker42 @bmw i am trying to  do the same even with updated instruction it is either misleading or does not help.
I am using amazon ec2 instance so not sure about the subscription how ever i tried the yum way to install .please find below my repositories i cannot get optional repository hence not able to install "python-zope-interface".
Please advise how you proceeded or succeeded. can we skip this using "--skip-broken" option??

[root@ip-172-31-32-219 src]# yum repolist
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
repo id                                                                  repo name                                                                                status
epel/x86_64                                                              Extra Packages for Enterprise Linux 7 - x86_64                                           10,818
mongodb-org-3.4/7Server                                                  MongoDB Repository                                                                          100
rhui-REGION-client-config-server-7/x86_64                                Red Hat Update Infrastructure 2.0 Client Configuration Server 7                               6
rhui-REGION-rhel-server-releases/7Server/x86_64                          Red Hat Enterprise Linux Server 7 (RPMs)                                                 13,379
rhui-REGION-rhel-server-rh-common/7Server/x86_64                         Red Hat Enterprise Linux Server 7 RH Common (RPMs)                                          209
repolist: 24,512

**Comment by kavikon** [comment]
@draker42 @bmw I got it to work. may be you need to mention the redhat users to download the python-zope-interface-4.0.5-4.el7.x86_64.rpm package from centos 7.2 distribution and install usimg rpm  rom https://rpmfind.net/linux/RPM/centos/7.2.1511/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.html link before proceeding 
 to install certbot.

**Comment by evenme** [comment]
Besides EPEL, I run the installation using:
`yum install python-certbot-apache --enablerepo=rhel-7-server-optional-rpms`
