### ISSUE TITLE
Certbot docs need to explain how to get libffi-devel on redhat 6.8

### ISSUE THREAD

**Issue by jsoref** [certbot/website#183]
https://certbot.eff.org/#centosrhel6-apache

https://www.redhat.com/archives/rhelv6-list/2015-December/msg00001.html

Someone else complained over a year ago on a Red Hat ML about letsencrypt-auto not working out of the box on rhel6.8:
> I am referring to
> https://letsencrypt.readthedocs.org/en/latest/using.html#third-party-plugins
>
> and i am getting *No package libffi-devel available*. Please find below the
> console output. Any help will be highly appreciable.

The "answer" was:
> libffi-devel is in the rhel-x86_64-server-optional-6 channel/repo:

It'd be helpful if either the certbot page addressed the need for this magic.
There's already talk about how to handle EPEL.

see also https://github.com/certbot/certbot/issues/3992

**Comment by jsoref** [comment]
afaict, the magic is: `rhn-channel --add --channel=rhel-x86_64-server-optional-6`

**Comment by SwartzCr** [comment]
Good call, made a PR with some updated documentation in #192, want to take a look at it and see if it is suitable?
(p.s. thanks for the great well written issues!)

**Comment by bmw** [comment]
While this could probably be improved, our current instructions link to https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F which has a note about enabling the optional repo with instructions on how to do it depends on your setup. Because of this, I'm closing this issue.
