### ISSUE TITLE
Document how to handle HTTPS_PROXY w/ certbot-auto

### ISSUE THREAD

**Issue by jsoref** [certbot/website#185]
https://github.com/certbot/certbot/issues/3480 indicates that `HTTPS_PROXY` and `sudo` aren't compatible. There should be documentation explaining what to do.

**Comment by SwartzCr** [comment]
I'd prefer to just see certbot/certbot#3480 resolved rather than adding something to the documentation that'll quickly get stale, but I'd be willing to have @bmw convince me otherwise

**Comment by SwartzCr** [comment]
@bmw and I agree that this is a code fix and not a documentation problem, so for now follow it in the certbot/certbot repo
