### ISSUE TITLE
Tell people about our PPA

### ISSUE THREAD

**Issue by bmw** [certbot/website#198]
We have an official PPA for Ubuntu 14.04, 16.04, and 16.10 that people should prefer over the Ubuntu packages and `certbot-auto`. We should update our instruction generator to tell them about it.

@SwartzCr, I think this is pretty important. New packages provide a much better experience to our users and Let's Encrypt has had to do extra work to provide backwards compatibility to the old packages to Ubuntu. Can you help with this?

**Comment by SwartzCr** [comment]
sure, is it documented anywhere? If so I can copy it over into the instruction generator

**Comment by bmw** [comment]
Yeah. Instructions on how to use it can be found [here](https://launchpad.net/%7Ecertbot/+archive/ubuntu/certbot). Packages are there for Ubuntu 14.04, 16.04, and 16.10.

I'm not sure how to best structure that information though. The only other version of Ubuntu that's not EOL'd is Ubuntu 12.04 which gets EOL'd next month. Ubuntu 17.04 comes out next month too and the PPA's not currently set up for that.

**Comment by SwartzCr** [comment]
luckily the only versions of ubuntu mentioned in the instruction generator are those three, so hopefully if someone has 12.04 or 17.04 they'll pick the Ubuntu (other) option. Sound right to you?

**Comment by bmw** [comment]
Yeah that's probably right. After next month, we won't be telling anyone on Ubuntu to use `certbot-auto` and we'll have to see whether we want to recommend the PPA or the OS packages for 17.04. We can deal with that then though.
