### ISSUE TITLE
Certbot search functionality shows bad snippet

### ISSUE THREAD

**Issue by mfb** [certbot/website#201]
as per @jsha:

Steps to reproduce:

Visit
https://certbot.eff.org/docs/search.html?q=bootstrappers&check_keywords=yes&area=default

Expected result:

Shows "Developer Guide" in search results with a snippet.

Actual results:

Developer Guide
`<html>  <head><title>404 Not Found</title></head>  <body bgcolor="white">  <center><h1>404 Not Found</h1></center> <hr><center>nginx</center>  </body>  </html>  <!-- a padding to disable MSIE and Chrome friendly error page -->  <!-- a padd...`

Note that this is doubly weird:
- The Developer Guide is present, not a 404.
- The snipper shouldn't show HTML tags.

**Comment by mfb** [comment]
When I build the site on my laptop, it works fine. So not sure what's up.  The search page results in a request to http://certbot.local/docs/_sources/contributing.txt which loads fine.

Meanwhile the live site requests https://certbot.eff.org/docs/_sources/contributing.rst.txt which 404s

**Comment by SwartzCr** [comment]
hmm - it seems like someone probably made a bad build of the website? We should rebuild it soon anyway and see if that clears this up - also there was talk of building it in travis or making a build server  - want to comment on that issue @mfb? it's #189

**Comment by bmw** [comment]
This is my fault.

After @SwartzCr, @vbrown608, and I talked about the related issue #191  , my understanding was the `.txt` `_source` files were unnecessary and being incorrectly pushed to the website. I was planning on writing PR to ensure they weren't copied over, but in the mean time I've been removing them manually before pushing the site live.
