### ISSUE TITLE
The privacy policy's description of the information included in the user agent string is out-of-date

### ISSUE THREAD

**Issue by zjs** [certbot/website#232]
I don't think that the privacy policy is _incorrect_ as written, but it could be updated to more clearly reflect the changes made to the user agent in certbot/certbot#4354.

**Comment by bmw** [comment]
Good point. @SwartzCr, would you be able to take and/or delegate the task of making sure this gets updated?

**Comment by SwartzCr** [comment]
Okay I've brought it up with Kurt and Peter

**Comment by bmw** [comment]
This has been fixed.
