### ISSUE TITLE
Be more emphatic that these commands should be run on a server

### ISSUE THREAD

**Issue by SwartzCr** [certbot/website#239]
We've gotten two recent complaints that people tried to run the commands on their local machine. Maybe all instructions should mention that they should be run on a webserver

**Comment by bmw** [comment]
On https://certbot.eff.org, we say:
> To get instructions for Certbot, choose your server software and the system it is running on from the dropdown menus above. You can then pick "advanced" if you want less automation and more control.

Perhaps we should make this text more prominent and/or also put something at the top of the generated instructions.

**Comment by SwartzCr** [comment]
we could add a note: to the top of all install instructions?
This would make it obvious that you're supposed to install certbot on your server, but could be confusing for people who want to use webroot from their personal computer. What do you think?

**Comment by bmw** [comment]
Yeah. To accomplish that we should be able to just modify `_scripts/instruction-widget/templates/instructions.html`.

I think the number of people trying to run Certbot on a different machine than their webserver using the DNS or manual plugins or webroot and network file system is very small. With that said, they do exist. I think the ideal solution is to say something like:

In most cases, you should follow these instructions on the same machine as the server you want to obtain certificates for. If you'd like to run Certbot on a different machine, click here.

where here is a link to documentation describing different ways to do that and the challenges involved.
