### ISSUE TITLE
Improve search engine findability for help pages

### ISSUE THREAD

**Issue by jsha** [certbot/website#261]
The current one-page design is nice and fast, but it's hard for search engines to find. For instance, the instructions to install on Ubuntu are at https://certbot.eff.org/#ubuntutyakkety-apache. Because the locator for that specific page is based on a URL fragment instead of the whole URL, search engines see it as identical to https://certbot.eff.org/.

We should break out each platform/software combination into its own page, with a full URL, like https://certbot.eff.org/lets-encrypt-ubuntu-yakkety-apache. Note that the # is removed, and the keywords people are likely to search for are separated out with hyphens. We should also ensure each page has a title that reflects what the page is about, e.g. "How to get a Let's Encrypt certificate on Ubuntu with Certbot and Apache," and a 1-sentence blurb at the top to give context to people arriving directly from a search rather than from the main page.

**Comment by vbrown608** [comment]
I'd like to get a final decision on the paths for these pages. In #295 I put them at, eg, certbot.eff.org/i/arch-apache. Do we want to tweak that to include a keyword about letsencrypt? We could do certbot.eff.org/lets-encrypt-instructions/arch-apache, for example.

**Comment by jsha** [comment]
Yeah, I think the latter would be good. We could leave out "instructions" since it makes the URL longer and is unlikely to be a search term IMO. So e.g. certbot.eff.org/lets-encrypt/arch-apache.

**Comment by zoracon** [comment]
Pre-redesign, closing
