### ISSUE TITLE
Update Debian backports instructions

### ISSUE THREAD

**Issue by bmw** [certbot/website#283]
Stretch users should use `stretch-backports` and Jessie users should use `jessie-backports-sloppy`.

**Comment by bmw** [comment]
We should make sure that packages are in these repos before we push these changes to the live site.

**Comment by SwartzCr** [comment]
lol - It would have been nice to have been mentioned in this comment so that I would have noticed to do this before @mrphs emailed me about it. Working on a PR now

**Comment by bmw** [comment]
I mentioned this issue to you in #285 and also thought I brought it up verbally a while ago, but I'm sorry you weren't as aware of the problem as you'd have liked. If in general there are categories of issues you'd like me to mention you on or things I can do to better communicate the state of the project to you, let me know.

It's worth noting that a newer version of Certbot is not yet in `jessie-backports-sloppy`. I brought this up to Harlan last week and he's going to work on changing that.

**Comment by SwartzCr** [comment]
Okay I made a commit, that at least fixes it for stretch, and we can fix it again when we're in jessie sloppy

**Comment by alexzorin** [comment]
Any news on getting into `jessie-backports-sloppy`?

If Certbot is not going to land there, perhaps the instructions could be updated to use `certbot-auto`, as the instructed `jessie-backports` is giving an ancient version.
