### ISSUE TITLE
Remove leading $ from shell command snippets

### ISSUE THREAD

**Issue by archfrog** [certbot/website#301]
Hi,

I'd just like to suggest that you remove the dollar signs ($) used to indicate the shell prompt in front of all shell command snippets on the [Certbot website](https://certbot.eff.org) so that this:

    $ sudo apt-get update
    $ sudo apt-get install software-properties-common
    $ sudo add-apt-repository ppa:certbot/certbot
    $ sudo apt-get update
    $ sudo apt-get install python-certbot-nginx

becomes:

    sudo apt-get update
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:certbot/certbot
    sudo apt-get update
    sudo apt-get install python-certbot-nginx

The reason that I **suggest** this is that the latter is much easier to copy and paste quickly.  With the latter, you can simply mark the five lines of text and insert them into your console/ssh session and you're done.  With the former, you have to waste time fiddling around with copying each line one at a time to remove the dollar sign.

I know this may not seem a big thing, but if you do two or three guides in an evening to get a server set up, you end up being rather tired of the very idea that shell commands should be prefixed by a dollar sign :-)

Cheers,
Mikael Egevig/Archfrog

**Comment by EdOverflow** [comment]
Hey fellow frog,

Let me submit a PR quickly to resolve this issue.

**Comment by archfrog** [comment]
Thanks, ribbit! :-)

**Comment by bmw** [comment]
I agree with the suggestion here that it'd be nice if the generated instructions were easy copy and paste, but I personally think having the leading `$` is kind of nice. I wonder how hard it would be to make it so the `$` wasn't selected if the user tried to select and copy these instructions.

@vbrown608, my HTML/JavaScript fu is pretty weak. Do you know how hard this would be?

If it's difficult, we probably should just take #307.

**Comment by vbrown608** [comment]
We could do this with a :before pseudo-element, something like
```
.prompt:before {
  content: "$";
}
```
Then each instruction line would need to be wrapped in an element with the .prompt class.

**Comment by RalphCorderoy** [comment]
I think the '$ ' being shown is more normally only done when output from the commands is interspersed so you can tell what's command and what's output. If it's only commands to paste, with nothing else being shown, then there is little benefit from them being present?

**Comment by bmw** [comment]
The `$` is still there, but it's selected when you go to copy the instructions so I'm closing this.
