### ISSUE TITLE
Redirect fedora24 id to fedora

### ISSUE THREAD

**Issue by bmw** [certbot/website#323]
Once upon a time, we had different instructions for different Fedora versions. Back then, we used the id `fedora24` to refer to Fedora 24+ instructions where Certbot was packaged. Fedora 24 is now EOL'd and the oldest version of Fedora that's still supported is Fedora 26.

I'd like to change the id used for Fedora in the instruction generator to just be `fedora`, but I don't want to break any links people have to the site since the `fedora24` instructions are identical to the instructions for all Fedora versions now: Get Certbot from your OS package manager.

@vbrown608, do you have any ideas on the best way to accomplish this?

**Comment by vbrown608** [comment]
@starchy can we do this with nginx?

**Comment by starchy** [comment]
Is this just a URL rewrite or is there anything else required?

**Comment by vbrown608** [comment]
Yep, just a rewrite.

**Comment by starchy** [comment]
@bmw since I think we're talking about an EFF infrastructure change, not a code change, do you want to open a ticket in that bug tracker listing the URL mappings?

**Comment by bmw** [comment]
Sure I'll open a ticket.

@vbrown608, to make this a smooth transition, I think it'd be good if we served the instructions for both the `fedora` and `fedora24` ids. Is there an easy way to do this without adding a 2nd Fedora option in the drop down menu?
