### ISSUE TITLE
FAQ contains outdated TLS-SNI

### ISSUE THREAD

**Issue by chrisfahr** [certbot/website#326]
"Can I issue a certificate if my webserver doesn't listen on port 80?

Yes, using the TLS-SNI-01 challenge. At the moment, Certbot only implements this challenge for Apache. If you’re using the webroot mode, your webserver must listen on port 80."

TLS-SNI has been disabled by LE. So at least for the usual case this will not work.
You could hint at the DNS challenge, though.

**Comment by bmw** [comment]
This has been resolved.
