### ISSUE TITLE
Remove Ubuntu Yakkety 16.10

### ISSUE THREAD

**Issue by joohoi** [certbot/website#328]
Ubuntu 16.10 should be removed from the website as it reached end of life in July 2017, and the packages aren't built for it in the PPA anymore.

**Comment by bmw** [comment]
I believe this is fixed in #309.

**Comment by joohoi** [comment]
Oh, right, closing!

**Comment by bmw** [comment]
I don't mind if this issue stays open if you prefer, just wanted to link the issue and PR!

**Comment by joohoi** [comment]
There's no real need as a PR already exists. It should be merged soon(ish) as people have hit it and falsely believed that Ubuntu PPA still ships packages for Yakkety.

**Comment by bmw** [comment]
Sure. I'll try to get to it soonish, but feel free to try and review it yourself. Happy to answer any questions that come up.

**Comment by joohoi** [comment]
Ok, will do!
