### ISSUE TITLE
Automatic renewal cron and PATH issues

### ISSUE THREAD

**Issue by patricktokeeffe** [certbot/website#343]
[These](https://certbot.eff.org/lets-encrypt/debianother-nginx) instructions are out-of-date and result in failed certificate renewals:
```
0 0,12 * * * python -c 'import random; import time; time.sleep(random.random() * 3600)' && ./path/to/certbot-auto renew 
```

https://github.com/certbot/website/blob/4c0fc14c139f6f2ad9a366288bd6e0ceade3ba4c/_scripts/instruction-widget/templates/getting-started/renewal.html#L39

----

With Nginx on Debian (Other), running the script in test mode results in success...
```
$ sudo /usr/sbin/certbot-auto renew --dry-run >> /home/pokeeffe/cli.log 2>&1
```
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/airops.paccar.wsu.edu.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator nginx, Installer nginx
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for airops.paccar.wsu.edu
Waiting for verification...
Cleaning up challenges

-------------------------------------------------------------------------------
new certificate deployed with reload of nginx server; fullchain is
/etc/letsencrypt/live/airops.paccar.wsu.edu/fullchain.pem
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/airops.paccar.wsu.edu/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
-------------------------------------------------------------------------------
```

but the same command in `cron` results in failure...
```
# sudo crontab -e
...
20 8,14 * * * python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/sbin/certbot-auto renew >> /home/pokeeffe/cron.log 2>&1
```
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/airops.paccar.wsu.edu.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()
Attempting to renew cert (airops.paccar.wsu.edu) from /etc/letsencrypt/renewal/airops.paccar.wsu.edu.conf produced an unexpected error: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError(). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/airops.paccar.wsu.edu/fullchain.pem (failure)

-------------------------------------------------------------------------------

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/airops.paccar.wsu.edu/fullchain.pem (failure)
-------------------------------------------------------------------------------
1 renew failure(s), 0 parse failure(s)
```

which is very counter-intuitive.

The install guide makes no mention, but it seems to be a fairly well known issue caused by PATH not containing `/sbin`. 

* https://github.com/certbot/certbot/issues/4937 
* https://github.com/certbot/certbot/issues/1833
* https://community.letsencrypt.org/t/server-doesnt-update-certificates-automatically/55191/4

I didn't find a canonical solution, but exporting the user's PATH and copying into crontab seemed like a popular choice (and it worked for me):
```
# sudo crontab -e
...
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
20 8,14 * * * python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/sbin/certbot-auto renew >> /home/pokeeffe/cron.log 2>&1
```

**Comment by bmw** [comment]
Thanks for the detailed issue @patricktokeeffe. I agree we need to do something here. I'm curious though, what distro are you using? The crontab included in the packages for every non-EOL'd version of Debian automatically works around this. See https://salsa.debian.org/letsencrypt-team/certbot/certbot/blob/master/debian/certbot.cron.d.

**Comment by patricktokeeffe** [comment]
Oops missed your comment @bmw.. Also oops, thought I mentioned it was Raspbian Jessie. I just looked into `/etc/cron.d/` and did find a `certbot` file with working PATH spec. 

Maybe checking for that file should be the 'quick start' version of automating, instead of the current instructions?

**Comment by bmw** [comment]
How about we just remove "Debian (other)" (and "Debian 7 (wheezy)" for that matter)? With instructions for Jessie, Stretch, and testing/sid, I think we have all Debian variants covered and the instructions for those systems tells you renewal has already been set up.

**Comment by patricktokeeffe** [comment]
I think that's very reasonable. I'd have chosen 'Debian (jessie)' if I hadn't seen 'Debian (other)' listed.

**Comment by bmw** [comment]
Great! Are you interested in making a PR? All that needs to be done is delete the "Debian (other)" and "Debian 7 (wheezy)" sections from https://github.com/certbot/website/blob/master/_data/inputs.json.

**Comment by robske110** [comment]
This seems to be fixed.
