### ISSUE TITLE
FAQ says "Certbot plans to add support for wildcard certificates when Let’s Encrypt starts issuing them."

### ISSUE THREAD

**Issue by collinanderson** [certbot/website#355]
FAQ says "Certbot plans to add support for wildcard certificates when Let’s Encrypt starts issuing them."

Seems out of date

**Comment by bmw** [comment]
Thanks for pointing this out! Are you interested in writing a PR to fix it?

The relevant file is https://github.com/certbot/website/blob/master/_faq_entries/7-wildcard.md.

**Comment by bmw** [comment]
Fixed in #356.
