### ISSUE TITLE
Docker instructions don't work on CentOS 6

### ISSUE THREAD

**Issue by schoen** [certbot/website#361]
Per https://community.letsencrypt.org/t/centos-6-dead-end-instructions/71903, we link to Docker instructions for getting DNS plugins on CentOS 6, yet the associated upstream Docker instructions themselves apparently declare that they're now incompatible with CentOS prior to version 7. So this isn't a viable path unless we can give a different set of instructions for Docker.

We might also want to find a way to emphasize more strongly the distinction between people needing a wildcard or not because we're still seeing false positives and false negatives on that (people trying to use `--apache` for wildcards or people trying to get DNS plugins for non-wildcard certs). I think the former case has been improving quite a bit.

**Comment by alexzorin** [comment]
CentOS 6 is no longer supported.
