### ISSUE TITLE
Tell Debian Jessie users to uninstall any Certbot packages from their OS

### ISSUE THREAD

**Issue by bmw** [certbot/website#377]
As pointed out by jsha, having multiple copies of Certbot installed can confuse users. Additionally, the version of Certbot in Debian Jessie comes with a cron job for renewal and doesn't respect Certbot's lockfiles. If the two versions of Certbot happen to get run at the same time, the user's files could become corrupted.

With us pointing users of Certbot packages that aren't seeing updates to https://certbot.eff.org, I think we can reduce some of the problem here by telling users to uninstall these packages before running `certbot-auto`.

I thought of a couple ways we could do this. The easiest (and maybe least useful) is just adding a generic message about removing any Certbot packages you've installed from your OS before using `certbot-auto`.

A more involved approach would be making this message Debian specific (as Debian Jessie is the only case we've ever told someone to switch from OS packages to `certbot-auto`) and might even help the user determine if these packages are installed and what commands to run.

**Comment by schoen** [comment]
https://github.com/certbot/website/pull/381 will fix this (I verified that the instructions that appear are Jessie-specific) but it might be wordier than really necessary.
