### ISSUE TITLE
`sudo certbot` vs. `sudo certbot-auto`

### ISSUE THREAD

**Issue by michielbdejong** [certbot/website#439]
In e.g. https://certbot.eff.org/lets-encrypt/centosrhel7-haproxy, `sudo certbot` in step 5 looks correct
But in https://certbot.eff.org/lets-encrypt/ubuntuother-other in step 3 it should probably be `sudo certbot-auto` instead, see https://github.com/certbot/certbot/issues/7219.

It looks like both pages include https://github.com/certbot/website/blob/master/_scripts/instruction-widget/templates/getting-started/certonly.html - can the executable name be parameterized for that template?

**Comment by michielbdejong** [comment]
I first thought I could fix it for ubuntu doing just https://github.com/michielbdejong/website-2/commit/6025a3c6337d3fde8a40cca3913b8c491074a24c but I guess that would break it for other operating systems.

**Comment by bmw** [comment]
Thanks for pointing this out @michielbdejong! Luckily, the name of the executable to run is already templated with the name `base_command` so I created a PR to fix this issue at https://github.com/certbot/website/pull/441.
