### ISSUE TITLE
How to test built versions of the site?

### ISSUE THREAD

**Issue by bmw** [certbot/website#443]
The instructions at https://github.com/certbot/website#travis-builds no longer seem to be accurate. At the very least, I'm getting problems because the URL we send users to for built instructions no longer ends in `.html`.

It might be due to the same problem, but I also can't get the wildcard instructions to load if I manually add `.html` to the URL.

What is the recommended way to see built versions of the site nowadays? @ohemorange, do you know or at least know who we can ask?

We should update the README with the new instructions.

**Comment by ohemorange** [comment]
I actually don't know, I wasn't able to get any version of building the site working. @esoterik do you know?

**Comment by esoterik** [comment]
I haven't actually used the builds repo to view the site -- I was running everything locally without docker for development, set up with the [readme instructions](https://github.com/certbot/website#without-docker)

**Comment by bmw** [comment]
I seem to have found a way to get the site running locally on port 12345 but it's not pretty. Check out the commit from the website-builds repo that you want to play with in your current working directory and run:
```
docker run -p 12345:4000 --rm -v /path/to/unbuilt/website/repo/nginx.conf:/etc/nginx/conf.d/default.conf:ro -v $(pwd):/usr/share/nginx/html:ro -it nginx
```
Before the redesign it seems we didn't need this [try_files](https://github.com/certbot/website/blob/99b24ca05bdc7b2dccff350dbfef70e4b59f0002/nginx.conf#L9) value, at least for the functionality I tested, but now we do (which is totally fine!).

I suppose `gulp` handles this automatically?
