### ISSUE TITLE
Fix uptime web hosting link

### ISSUE THREAD

**Issue by bmw** [certbot/website#455]
Website builds are failing at https://travis-ci.com/certbot/website/builds/120894065 due to https://github.com/certbot/website/blob/89932f8626b753348c4064084b140e20aad729fa/_data/hosting_providers.json#L1766 404ing.

Quickly looking around their site, I found https://uptimewebhosting.com.au/cpanel-website-hosting-plans/ which if you read carefully says you get can free certs from Let's Encrypt, but I couldn't find anything that says it still happens by default like it did at https://web.archive.org/web/*/https://uptimewebhosting.com.au/knowledgebase/5/Securing-your-website-with-cPanel-web-hosting-plans.html.

@ohemorange, do you have a preferred approach to fix issues like these?

**Comment by ohemorange** [comment]
Oh fabulous. IMO it's fine to have dead links with expired information, that's the point of the "reviewed" field. My preferred option would be to let the build pass regardless, ignoring the 404. If that's hard, I'd say comment out the whole entry for now and contact the provider asking for updated information.
