### ISSUE TITLE
Create web hosting provider page with information that users can select from the drop down

### ISSUE THREAD

**Issue by ohemorange** [certbot/website#468]
See page design here:

https://xd.adobe.com/view/6934cd71-399f-43c2-40a2-1a41b966eb34-1f05/screen/d03670a5-7076-4958-86f2-218a97d828b7/AFTER-USER-TESTS-Desktop-Certbot-WebHostingProvide/

**Comment by ohemorange** [comment]
Remove box.

Note: this doesn't apply to people using a VPS; you'll have to manually manage your Certbot installation, and select your OS from the dropdown above.

**Comment by okaysoraya** [comment]
Here's a more up-to-date wireframe.  
![After User Tests - Github Issues - Erica](https://user-images.githubusercontent.com/16709499/64899584-0238b580-d641-11e9-9b1b-17458d02e42c.png)

**Comment by lschatzkin** [comment]
@ohemorange This page needs to be created in the /_instructions directory, which I see is in .gitignore. How should I go about creating this page?

**Comment by ohemorange** [comment]
Pages in `_instructions` are generated from components, which live in various other directories but the ones you want are probably under `_scripts/instruction-widget/templates`. You may also have to modify a script in `_scripts/instruction-widget/`, maybe `install.js`. @esoterik would actually know better than me in general for questions about the codebase.

**Comment by lschatzkin** [comment]
Cool, that gives me a good starting point. Thank you!

**Comment by lschatzkin** [comment]
> Cool, that gives me a good starting point. Thank you!

Ah cool, I figured it out, thanks again for the tip @ohemorange !

**Comment by lschatzkin** [comment]
@ohemorange I need a little templating help. I'm trying to put a conditional in _layouts/instruction.html so the big "To use cerbot" box doesn't show up on the shared hosting page. I've tried a few things, something like:
`        {% if site.data.inputs.operating_systems.os="sharedhost" %}
         <p>test</p>
        {% else %}
         {% include use_certbot.html %}
        {% endif %}`

What am I doing wrong? Thanks!

**Comment by esoterik** [comment]
@lschatzkin 

I think you probably want to edit this file: `_scripts/instruction-widget/templates/getting-started/sharedhost.html` -- that's the html that gets rendered in the box when "Web Hosting Product" is selected!

**Comment by esoterik** [comment]
> @ohemorange I need a little templating help. I'm trying to put a conditional in _layouts/instruction.html so the big "To use cerbot" box doesn't show up on the shared hosting page. I've tried a few things, something like:
> ` {% if site.data.inputs.operating_systems.os="sharedhost" %} <p>test</p> {% else %} {% include use_certbot.html %} {% endif %}`
> 
> What am I doing wrong? Thanks!

oops, mis-read this, sorry: it might be best to do this with JS or by somehow checking the current url in jekyll. The select inputs are determined from the url via javascript when you navigate to the instructions page from the homepage, so that might be causing some weirdness.

**Comment by lschatzkin** [comment]
Great, I'll try that.

**Comment by lschatzkin** [comment]
@ohemorange Is this text final, or is there a final version of the text?

**Comment by ohemorange** [comment]
A couple small edits:

"If your hosting provider has Full Support" --> "If your hosting provider has full support"

"you're probably not the only one..." change ! to .

**Comment by okaysoraya** [comment]
Here's what I have as the text -- please feel free to make edits as you see fit. I included some minor notes around possible styling and links. The areas that are bolded are anticipated links.


#(style: heading before the fold) Web Hosting Product

#(style: bold, notification exclamation icon) Important note:
These instructions do not apply to people using a **Virtual Private Server (VPS)**; you’ll have to manually manage your Certbot installation, and select your Operating System from the dropdown above.

#(style: heading) Look for your web hosting provider on this list.

#(style: paragraph text) Are you looking for your web hosting provider, such as Squarespace, Github, or WordPress? 

You might already have HTTPS available and not need Certbot! **Find your web hosting provider in our chart of hosting providers**. 

#(button: **find your web hosting provider**)

#(style: paragraph text)
If your hosting provider has full support for HTTPS: good news! You won’t have to do anything further.

If your hosting provider has partial support for HTTPS: good news! You can follow along the linked tutorials for that individual web hosting provider, and get your website on HTTPS without needing Certbot.

If your hosting provider does not support HTTPS: continue to the steps below.


# (style: heading) If your hosting provider does not support HTTPS, the following options are available:

# (style: smaller heading) You can contact your web hosting provider: tell them you want a free HTTPS certificate through Let’s Encrypt. 
# (style: paragraph text) You’re probably not the only one using your web hosting provider service who wants HTTPS. You can request that your web hosting provider offer Let’s Encrypt HTTPS certificates as a free part of their hosting package. An effective way to make this ask is through email, their help desk system, or by contacting the web hosting provider through social media.

# (style: smaller heading) You can switch to a different web hosting provider.
# (style: paragraph text) Find a web hosting provider who offers full HTTPS support as part of their web hosting package by **checking our list**.

# (style: smaller heading) You might be able to use Certbot.
# (style: paragraph text)  If you have **SSH access** to the server your website is hosted on, you might be able to use Certbot. You will need to know the **software** and **system** your server is running on. After you confirm the software and system information, you can use the dropdown menus above to generate specific instructions for running Certbot on your server through the command line. 


—
# (style: smaller text after completing task)
Was this information helpful?
Certbot is a free project provided by the
Electronic Frontier Foundation, a 501(c)3 nonprofit.
We’d be grateful for your support.

# (style: button: **Donate to Certbot and EFF**)

**Comment by lschatzkin** [comment]
Great, thank you @okaysoraya !

**Comment by lschatzkin** [comment]
I'm assuming the three icons on the bottom of the page are being removed? Is this just for this instruction 
![Screenshot from 2019-12-03 11-24-02](https://user-images.githubusercontent.com/852512/70082560-89058a80-15bf-11ea-9480-f46c3d44040a.png)
page or for all pages?
