### ISSUE TITLE
Move page title above box for results of certbot instructions page

### ISSUE THREAD

**Issue by ohemorange** [certbot/website#469]
So people can see that the contents changed without having to scroll

**Comment by wioux** [comment]
Just a thought but maybe we should remove the box altogether from instructions and just have it on the homepage? My intuition is that after someone has navigated to something like Apache on Debian, instructions that they first need an _HTTP website_ **(?)**, which is hosted on a _server_ **(?)**, etc., is not the content they are looking for or definitions they need. Those clarifications may be useful on the homepage, but the context coming into the installation instructions is that they've just told us "My HTTP website is running [Software] on [System]".

**Comment by lschatzkin** [comment]
A good point, let's ask  @okaysoraya
