### ISSUE TITLE
Keep instructions in sync with package name transitions

### ISSUE THREAD

**Issue by mfb** [certbot/website#52]
e.g. currently Ubuntu 16.04 instructions specify to `apt-get install certbot` but this won't work until the certbot package is actually uploaded. 

For each distro (Debian, Fedora, Ubuntu, etc.) we need to update the instructions as package names are updated.

@todo figure out which distros will be updating package names and when? For example, the FreeBSD port?

**Comment by SwartzCr** [comment]
@hlieberman any movement?

**Comment by SwartzCr** [comment]
18:00 < hlieberman> swartzcr: certbot packages are in unstable.
18:00 < hlieberman> Will migrate to testing in 4 days.
18:01 < hlieberman> And I'll be targeting Ubuntu for around then as well.

**Comment by SwartzCr** [comment]
for review https://github.com/certbot/website/pull/105

**Comment by SwartzCr** [comment]
I'm going to close this for now since we're up to date with debian and ubuntu and other people are opening new tickets for other OSs
