### ISSUE TITLE
Instrcution s Documentation Update

### ISSUE THREAD

**Issue by CBDFactum-com** [certbot/website#549]
Hi,

I am referring to this page: [https://certbot.eff.org/instructions](https://certbot.eff.org/instructions).

A new entry for “Apache” and the System selection list “SLES 15.1” could be added.
Below I list the commands for point 2 “Install Certbot” - it’s almost the same like for openSUSE Leap 15.0 but it needs commands which add the packages so `zypper` can install `certbot` and the depending packages.

- `SUSEConnect -p PackageHub/15/x86_64`

- `SUSEConnect -p sle-module-python2/15.1/x86_64`

- `zypper install certbot python-certbot-apache`

The other points can remain as they are.

**Comment by bmw** [comment]
This issue looks like it was identical to the first version of https://github.com/certbot/website/issues/554 so I'm assuming two issues were created on accident and I'm closing this issue. If that's incorrect, please let me know!
