### ISSUE TITLE
Header of the page stays active after selecting software and distribution

### ISSUE THREAD

**Issue by joohoi** [certbot/website#55]
Header box has active "borders" after selection.

Chrome Version 50.0.2661.94 (64-bit) on OS X 10.10.5

<img width="800" alt="title_bug" src="https://cloud.githubusercontent.com/assets/5235109/15192497/23d28ec8-17c2-11e6-9c09-638d0e009bde.png">

**Comment by SwartzCr** [comment]
closing this, feel free to re-open if you see fit
