### ISSUE TITLE
Add banner pointing people to snapd?

### ISSUE THREAD

**Issue by bmw** [certbot/website#559]
Currently we're planning on suggesting the majority of our users use the Certbot snap in the future because it provides an easy way for most users to get the latest version of Certbot with things like automatic renewal preconfigured.

I added a snap dropdown to the instruction generator at https://github.com/certbot/website/pull/558, but I think it may be worth having the instructions for systems that can use the snap suggest people try it too. Installing Certbot in this way will first go through a beta period which this banner should probably make clear, however, I think it would encourage many more people to try it.

I think it probably makes sense to start the Certbot snap beta without this change and then consider it if not many people are using it.

**Comment by bmw** [comment]
The list of OSes in the instruction generator this banner is relevant for is:

* Debian 9
* Debian 10
* Debian testing/unstable
* All versions of Ubuntu
* Arch Linux
* Fedora
* CentOS/RHEL 7
* CentOS/RHEL 8
* All openSUSE versions

The banner should also probably not be shown if the user selects "Plesk" in the software dropdown as those instructions do not tell you to install Certbot.

Proposed banner text is something like:

> If you would like to help test a new way to install Certbot that automatically renews your certificates and stays up-to-date, please choose "snapd" in the system dropdown above.

A nicer but harder to implement approach would be to automatically link to those instructions, however, the URL to use would depend on the value the user chose in the "system" dropdown.

**Comment by lschatzkin** [comment]
Hi Brad, some questions:

- Where do you want this banner to appear? Right now there's text if the user chooses the system but not the software. Does this banner supersede that text?
- Does it show up in the same place?
- Did you want this text to only show when certain OSs are chosen? 
![Screenshot from 2020-06-10 15-37-17](https://user-images.githubusercontent.com/852512/84326052-f8d96c80-ab30-11ea-9872-04f8abe62de0.png)

**Comment by bmw** [comment]
Hey Artemis :wave:

My eye for this kind of stuff is probably worse than most so feel free to suggest/make changes from my answers.

To try to give you a little more context for what we're trying to do here, snaps are a new way to install Certbot that can be used on most but not all systems. We'd like people who can use snaps to help us test it before we update the instructions for all eligible systems to use the snap instead of their current instructions.

> Where do you want this banner to appear?

After you choose both system and software you'll get a page containing something like:

![Screen Shot 2020-06-10 at 4 01 23 PM](https://user-images.githubusercontent.com/6504915/84327223-ad748d80-ab33-11ea-9fcf-01649ba4d5a5.png)

I would put the banner before the numbered instructions which in this case starts with "SSH into the server". If the banner is in the box, it should be shown for both the "default" and "wildcard" tab.

> Right now there's text if the user chooses the system but not the software. Does this banner supersede that text?

I don't think so. We could maybe show both and/or update the text to suggest snapd, but I think the current text is more important than the banner.

> Did you want this text to only show when certain OSs are chosen?

I think that would be nice to avoid things like our Windows instructions suggesting people try snaps which won't work for them. I put a list of systems that could use the snap in my previous post. If this is tricky, we could probably always show the banner since the majority of our users can use the snap.

**Comment by lschatzkin** [comment]
Okay, I'll get started and then probably have more questions. Thanks!

**Comment by lschatzkin** [comment]
It seems to put the text there, and do it by OS, I'd have to change the markdown files in /instructions, but this directory is in .gitignore. Do you know why?

**Comment by bmw** [comment]
I think those files are generated by the code under `_scripts/instruction-widget`.

**Comment by lschatzkin** [comment]
ah ha! Okay, I'll see what I can do there.
