### ISSUE TITLE
Ubuntu 20.04 nginx instructions

### ISSUE THREAD

**Issue by bmw** [certbot/website#570]
People are actively working on https://bugs.launchpad.net/ubuntu/+source/python-certbot-nginx/+bug/1875471/, but it'll be a few days, if not a couple weeks, before the problem is resolved.

I'd like to fix our instructions in the meantime. Unfortunately, I think we're in a bit of a tricky spot with certbot-auto not currently working on Ubuntu 20.04 and no PPA packages available for the system with no Debian/Ubuntu developers planning to help with this in the short term.

For now, I think we should:

1. Split Ubuntu 19.10+ to Ubuntu 19.10 and Ubuntu 20.04. (I think Ubuntu 19.10 can keep the "ubuntuother" id since the nginx plugin should work on every other Ubuntu version and when the problem is fixed, we can merge the two again and create a redirect from Ubuntu 20.04 to ubuntuother if we want.)
2. Our instructions for nginx should treat the nginx plugin as unpackaged and list our certonly instructions.

As an alternate to (2), we could make sure that the nginx plugin works as an installer and provide instructions to use webroot/standalone with the nginx installer, but I personally don't think this work is necessary for what should be a short term setup and it causes problems such as https://github.com/certbot/certbot/issues/5486.

@ohemorange, can I get a +1 on this plan? If you agree I'll write a PR for it (or you can if you're interested and I'll review it).

**Comment by ohemorange** [comment]
Agree, will review, thanks! And additionally agree it doesn't make sense to bother listing nginx as an installer.
