### ISSUE TITLE
Give the wildcard tab its own URL

### ISSUE THREAD

**Issue by bmw** [certbot/website#573]
As reported by @jsha:

> the wildcard tab doesn't seem to have its own URL, which would be a nice thing to add so people can link directly to it.

I agree. Since the instructions are different (in some cases dramatically), it'd be nice if you could link to each individually.

**Comment by osirisinferi** [comment]
I don't understand why, but this feature implemented almost 2 years ago seems to be *gone*? The wildcard tab does not have a separate URL any longer and adding the `#wildcard` fragment identifier doesn't do anything any longer..

**Comment by bmw** [comment]
cc @zoracon

I initially brought up that this was broken in the internal certbot.eff.org channel 11 months ago.

**Comment by zoracon** [comment]
I will bring this back up in the internal site channel. I want to believe I listed all the original breakage but it possible that got missed because either 1. I did not list that or 2. It was forgotten in the mix. Either way, I will follow up on this one.
