### ISSUE TITLE
Simplify using Travis Builds

### ISSUE THREAD

**Issue by bmw** [certbot/website#579]
The instructions at https://github.com/certbot/website#travis-builds seemed to break during the website redesign as I initially reported at https://github.com/certbot/website/issues/443. https://github.com/certbot/website/pull/578 attempted to sort of make things work, but it's not pretty.

Is there anything we can do to simplify this? The best idea that initially springs to mind would be to provide a script/Docker setup in this repository that automatically fetches things a branch from the website-builds repository where the branch name is given as an environment variable or command line flag.

**Comment by bmw** [comment]
Another idea I had here was to push `nginx.conf` in the root of this repo to the website-builds repo and write a script/command that configures nginx to use this file and host the other files in the repo. If the command is complicated, a script probably makes the most sense and maybe we could also push the script to website-builds and have nginx configured not to serve it?

If this approach is taken, I think ideally the real nginx server hosting certbot.eff.org would then be configured to use this file which would help with #584. This would require some work/trust/coordination from tech ops, but I think we could probably find something that makes everyone happy here.

**Comment by adferrand** [comment]
Could https://github.com/certbot/website/pull/513 be somewhat relevant here?

**Comment by bmw** [comment]
I personally think we should probably keep the Docker setup that builds and runs the site locally through `gulp` separate from the setup of just serving the files built in CI and pushed to website-builds.
