### ISSUE TITLE
Broken markup in Windows instructions

### ISSUE THREAD

**Issue by alexzorin** [certbot/website#588]
https://certbot.eff.org/lets-encrypt/windows-other

It looks like something is going wrong with the `<ol>`  under *Installation instructions*.

![markup in text](https://i.imgur.com/WNdLCFh.png)

and

![markup in text and section 5 does not exist](https://i.imgur.com/g3bm1Ux.png)

**Comment by schoen** [comment]
I believe this can be fixed with #590 now—at least the `</ol>` renders properly there now!

**Comment by alexzorin** [comment]
Thanks @schoen!

**Comment by schoen** [comment]
Now even better due to https://github.com/certbot/website/pull/601!
