### ISSUE TITLE
openSUSE tumbleweed: python-certbot-* should be python3-certbot-*

### ISSUE THREAD

**Issue by alexzorin** [certbot/website#597]
On tumbleweed version 20200611:

    # zypper install python-certbot-apache
    Reading installed packages...
    Package 'python-certbot-apache' not found.

It looks like that name no longer points to a valid package, and `python3-certbot-apache` needs to be specified.

**Comment by ohemorange** [comment]
Nice catch, thanks! Looks like this is true on Leap as well: https://pkgs.org/search/?q=certbot
