### ISSUE TITLE
Bitnami intsructions

### ISSUE THREAD

**Issue by alexzorin** [certbot/website#612]
Would you take a PR to link to https://docs.bitnami.com/general/faq/administration/generate-configure-certificate-letsencrypt/ for Bitnami environments? I am not sure if you're willing to list too many snowflake environments in the dropdowns, and it would mean having to make sure it doesn't turn into a dead link.

Certbot + Bitnami = trouble is a regular topic which crops up. I think it would be helpful to have a signpost in the dropdown list.

**Comment by ohemorange** [comment]
@bmw thoughts?

**Comment by bmw** [comment]
If in your opinion Certbot + Bitnami = trouble is a regular topic which crops up, I'd personally be fine with a PR like that adding "Bitnami" to the software dropdown and doing something similar to what we do with Plesk.

I think we shouldn't do this for any piece of software out there, but if we're seeing something become a recurring problem, I think listing it there to try to help avoid problems makes sense.
