### ISSUE TITLE
Change DNS plugin snap instructions to use `--beta` once they're on beta

### ISSUE THREAD

**Issue by ohemorange** [certbot/website#614]
Follow-up from / described in https://github.com/certbot/website/issues/603

See a1a03648264a441165dd64afdd2b3dbc5a178a53 in https://github.com/certbot/website/pull/613 for what to revert.

**Comment by bmw** [comment]
Our DNS plugins are in the beta channel now, but one reason we may want to keep the instructions on the edge channel is if https://forum.snapcraft.io/t/request-for-greedy-plug-certbot-plugin-interface/19190 is resolved, will the change apply to previously released snaps or just new releases going forward? If the latter, our snaps in the beta channel won't see the change until our next release.

**Comment by ohemorange** [comment]
That's a very good question. I can't say I fully understand where these rules are applied; my guess would be the `snapd` installer, but we should probably test it to be sure.

**Comment by bmw** [comment]
Since we're no longer planning to have people use the edge channel, I think we can close this.
