### ISSUE TITLE
Runtime Mustache rendering is causing raw Jekyll markup to appear 

### ISSUE THREAD

**Issue by alexzorin** [certbot/website#626]
While working on #612 I've been seeing some pretty ugly <a href="https://en.wikipedia.org/wiki/Flash_of_unstyled_content">FOUC</a> (well, more like Flash of Template Code) when I select a webserver/distro.

[Video example](https://tools.letsdebug.net/certbot-jekyll-fouc.mp4).

Two things seem to be happening:

- Upon input selection, `document.location.href` is changed and the browser begins navigating to the new URL via full page reload
- While that navigation happens, the mustache template is *also* being rendered. That template's output contains raw Jekyll markup such as:

```html
<div class="tab advanced">wildcard{% include tooltip.html term-name="wildcard-certificate" text="*" %}</div>
```

which you can see being rendered in the video.

Some time later, depending how fast the network is, the full page navigation completes and the unwanted markup disappears - since the static version of the page is properly rendered.

In my opinion, removing runtime mustache rendering entirely would be no big loss. I had a quick look around and I don't think the site actually relies on it in any way that can't be reasonably substituted with full navigation.

Otherwise, let's fix the mustache templates so they are not spitting out Jekyll markup.

I understand that perhaps not the most time can be afforded to this repo, but since this could be fixed by deleting code only, maybe it's worth it.

**Comment by bmw** [comment]
Thanks a lot for digging into this and writing this up Alex.

I'll bring this up with EFF's Engineering and Design team who wrote and maintains most of the tech behind this site. Like you said, I'm not sure they'll be able to prioritize this right now, but we'll see!

**Comment by lschatzkin** [comment]
It seems to me that somehow the static site (  _site) is not being served but I have not yet deduced why.
When I look at docker-compose.yml on line 19 it says `  - assets:/opt/certbot/_site` so that seems correct to me.
I'm not seeing anything in the other build files that contradicts this.
Dockerfile has `CMD ["gulp", "jekyll:watch"]` on line 70 but I believe that's just for css/js

**Comment by bmw** [comment]
If parts of the site aren't loading for you at all with our Docker setup, the issue for that is https://github.com/certbot/website/issues/621. In general, we've been struggling to build and test this site which I think Max has been talking with Lena about.

What we've been doing instead which I believe closely mimics how the live site is hosted is making use of the website-builds repository described at https://github.com/certbot/website#building-with-travis.

**Comment by alexzorin** [comment]
From what I can remember, the code flash is from this:

https://github.com/certbot/website/blob/087a1657e79b9445f3f66dc4df8d8d218ca355f7/_scripts/instruction-widget/main.js#L104-L115

That `instructions.render()` call is rendering the bundled Mustache template, which contains raw Jekyll markup.

And indeed, that template contains raw Jekyll markup:

https://github.com/certbot/website/blob/087a1657e79b9445f3f66dc4df8d8d218ca355f7/_scripts/instruction-widget/templates/instructions.html#L2-L4

I do not see how this would even work in theory. Jekyll would have to have take a pass over that template before the Mustache compiler got to it.

Is it perhaps the case that those templates are not supposed to contain Jekyll markup in the first place, but they snuck in because the flash of code is relatively unnoticeable?

Sorry if I'm totally off-base here.

**Comment by lschatzkin** [comment]
> From what I can remember, the code flash is from this:
> 
> https://github.com/certbot/website/blob/087a1657e79b9445f3f66dc4df8d8d218ca355f7/_scripts/instruction-widget/main.js#L104-L115
> 
> That `instructions.render()` call is rendering the bundled Mustache template, which contains raw Jekyll markup.
> 
> And indeed, that template contains raw Jekyll markup:
> 
> https://github.com/certbot/website/blob/087a1657e79b9445f3f66dc4df8d8d218ca355f7/_scripts/instruction-widget/templates/instructions.html#L2-L4
> 
> I am not sure how this is supposed to work in theory, so bear with me. It seems like Jekyll would have to have take a pass over that template before the Mustache compiler generated its bundle. I don't think that's happening.
> 
> Is it perhaps the case that those templates are not supposed to contain Jekyll markup in the first place, but it snuck in accidentally? Here is the commit which moved the Jekyll markup from `_layouts` to `_scripts/instruction-widget/templates`: [7a333d6](https://github.com/certbot/website/commit/7a333d6851c1836a19934845627bbd42620654b1)
> 
> Sorry if I'm totally off-base here.

Okay, I missed this bit of js and that would definitely be causing the problem. Thanks for pointing that out!

**Comment by lschatzkin** [comment]
I don't understand why they are being rendered either, but your fix works so let's go with that!
