### ISSUE TITLE
`snap.html` refers to "OS in the dropdown menu above" but is used by (some of) those same menu options, creating a circular reference

### ISSUE THREAD

**Issue by osirisinferi** [certbot/website#667]
Currently, the [snap instruction page](https://github.com/certbot/website/blob/5d4274d7bd183867f475e5090c96e162dba0c972/_scripts/instruction-widget/templates/install/snap.html) contains a banner at the top called "Snap support" with the text:

> You can find instructions for installing Certbot **without using snap by selecting your OS in the dropdown above**.

*However*, currently this same snap instruction page, which includes the above quoted reference, is used on many OS specific certbot installation instruction pages! Previously, only the "Snap" instruction page contained these Snap instructions, but currently, snap has become the main instruction for a few OS choices:

* [Arch, openSUSE, Other Linux](https://github.com/certbot/website/pull/648)
* [Fedora and RHEL &ge;7](https://github.com/certbot/website/pull/659)
* [Debian](https://github.com/certbot/website/pull/658)

So, for these OS'es, the instruction to choose the "OS in the dropdown" menu to get instructions for installing certbot *without* snap is a circular reference to the same snap instructions.

**Comment by ohemorange** [comment]
Thanks for reporting! This is currently the case because we're in the process of migrating all the OSes towards having a consistent installation approach. In the next couple of months we'll be cleaning up these instructions, so we'll make sure to avoid the circular reference when we do.

**Comment by osirisinferi** [comment]
@ohemorange I'm not sure if waiting for the required OSses aer migrated is the wise thing to do.. For example, there now has been opened a support thread on the Community very recently: https://community.letsencrypt.org/t/how-to-install-certbot-without-snap/137634

The current situation is very confusing..

**Comment by ohemorange** [comment]
My point is really that we are in the process of fixing this; this should be covered by the issue linked above, #8422.
