### ISSUE TITLE
Stop using submodules

### ISSUE THREAD

**Issue by bmw** [certbot/website#682]
git submodules are awful. On top of that, we regularly forget to update the submodule for the Certbot website. Is there something more usable we can do instead?

I'm not sure if there's code out there we can use for this on a site like readthedocs, but can we essentially just always build the docs for the latest tag on the Certbot repo with an easy way for us to override that if we want to update something between releases? (Bonus points if the system also helps us to remember to stop overriding the commit used in some way, however, I certainly do not think this is essential.)

**Comment by bmw** [comment]
What I personally think we should do here is to just start hosting our documentation on readthedocs.org. It allows us to stop using submodules, easily toggle through their UI which commit is used for the live documentation, and do things like by default always show the documentation for our latest git tag.

**Comment by adferrand** [comment]
I remember that something like two years ago, there were some PRs to remove last traces of a something looking like a Certbot documentation hosted on readthedoc.

Was it really the case? What was the reason if so to move away from it if so?

**Comment by bmw** [comment]
I think you're remembering https://github.com/certbot/certbot/issues/8155 which was about the letsencrypt readthedocs page that we struggled to make redirect to https://certbot.eff.org/docs.
