### ISSUE TITLE
Docs: Search Stuck Indefinitely

### ISSUE THREAD

**Issue by zoracon** [certbot/website#711]
Reported by: @jsha 

---

## Steps to reproduce:

    Visit https://certbot.eff.org/docs/search.html?q=acmev2&check_keywords=yes&area=default

The page shows "Searching..." indefinitely, and a JS error in the console:

Uncaught ReferenceError: Stemmer is not defined

    query https://certbot.eff.org/docs/_static/searchtools.js:158

    setIndex https://certbot.eff.org/docs/_static/searchtools.js:98

**Comment by alexzorin** [comment]
Had a go at this in https://github.com/EFForg/sphinx_rtd_theme/pull/6.

**Comment by bmw** [comment]
This is fixed.
