### ISSUE TITLE
macOS instructions suggest installing non-existing formulas

### ISSUE THREAD

**Issue by alexzorin** [certbot/website#752]
On the forums there have been a couple of threads where confused users have been trying to `brew install certbot-apache` or `brew install certbot-nginx`.

Turns out that the suggestion is coming from the instruction generator:

https://certbot.eff.org/instructions?ws=apache&os=osx

https://certbot.eff.org/instructions?ws=nginx&os=osx

**Comment by zoracon** [comment]
Issued a ticket with internal team. Will update when this gets patched.

**Comment by robske110** [comment]
I can't reproduce this (don't see the mentioned commands on the webpage). It it already fixed?

**Comment by bmw** [comment]
Yep! This has been fixed.
