### ISSUE TITLE
FreeBSD instructions suggest old package version

### ISSUE THREAD

**Issue by schoen** [certbot/website#762]
Hi!

Per a message at

https://community.letsencrypt.org/t/error-in-freebsd-certbot-install-instructions/171129/2

the Certbot website is suggesting an old package name (`py37-certbot`) in

https://certbot.eff.org/instructions?ws=apache&os=freebsd

Oddly enough, the website build at

https://github.com/certbot/website-builds/blob/master/lets-encrypt/freebsd-apache.html

shows the current name (`py38-certbot`). Is it possible that some documentation updates were lost in the migration to the internally-hosted version of the website, or something?

**Comment by alexzorin** [comment]
@zoracon not sure if you got notified, another one for E&D.

**Comment by alexzorin** [comment]
Another issue I have noticed is that if you select a webserver (e.g ngijnx) + FreeBSD:

- https://certbot.eff.org/instructions?ws=nginx&os=freebsd
- It does not prompt you to install the appropriate authenticator plugin e.g. `py38-certbot-nginx`
- The instructions do not prompt you to run `certbot --nginx`, whereas [the instructions for Ubuntu](https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal) do.

**Comment by utkonos** [comment]
This issue can be future-proofed by changing the command as follows.

On this page of the documentation:
https://certbot.eff.org/instructions?ws=other&os=freebsd

```sh
pkg install py37-certbot
```

Becomes:

```sh
pkg install security/py-certbot
```

This will choose the correct pyXX-cerbot and all its dependencies for installation. Here is the output from this command:

```
# pkg install security/py-certbot
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 31 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        gettext-runtime: 0.21
        indexinfo: 0.3.1
        libffi: 3.4.2
        mpdecimal: 2.5.1
        py39-acme: 1.31.0,1
        py39-certbot: 1.31.0,1
        py39-certifi: 2022.6.15
        py39-cffi: 1.15.1
        py39-charset-normalizer: 2.1.1
        py39-configargparse: 1.5.3
        py39-configobj: 5.0.6_1
        py39-cryptography: 3.4.8
        py39-distro: 1.7.0
        py39-idna: 3.3
        py39-josepy: 1.13.0
        py39-openssl: 20.0.1,1
        py39-parsedatetime: 2.6
        py39-pycparser: 2.21
        py39-pyrfc3339: 1.1
        py39-pysocks: 1.7.1
        py39-pytz: 2022.5,1
        py39-requests: 2.28.1
        py39-requests-toolbelt: 0.9.1_1
        py39-setuptools: 63.1.0
        py39-six: 1.16.0
        py39-urllib3: 1.26.12,1
        py39-zope.component: 4.2.2
        py39-zope.event: 4.1.0
        py39-zope.interface: 5.3.0
        python39: 3.9.15
        readline: 8.1.2

Number of packages to be installed: 31

The process will require 149 MiB more space.
22 MiB to be downloaded.

Proceed with this action? [y/N]:
```

This is noted on Freshports as well as in this issue:
https://github.com/certbot/certbot/issues/9394

**Comment by bmw** [comment]
This has been fixed.

**Comment by bmw** [comment]
Thanks for pointing that out. I'm still trying to figure out this new CMS I just got access to 🙃 

That's fixed now too.

**Comment by utkonos** [comment]
No worries. It looks like the change didn't propagate yet:
https://certbot.eff.org/instructions?ws=other&os=freebsd

**Comment by zoracon** [comment]
Closing out since this is fixed now with suggesting `pkg install security/py-certbot-apache`
