### ISSUE TITLE
Add MidnightBSD instructions

### ISSUE THREAD

**Issue by laffer1** [certbot/website#773]
Would it be possible to get MidnightBSD added to the list of operating systems on the eff certbot page? It's been available from mports and in package form for several years now.

Instructions for installation on MidnightBSD via packages

standalone:
mport install py38-certbot

apache:
mport install py38-certbot-apache

nginx:
mport install py38-certbot-nginx

(python 3.8 is default on MidnightBSD currently)

mport is the package manager and mports is what we call our ports tree. These are based on FreeBSD ports, so pretty much work the same.

The MidnightBSD mports repository is at https://github.com/midnightbsd/mports if you want to look at the implementations here.

We currently offer
py-certbot
py-certbot-apache
py-certbot-dns-google
py-certbot-dns-ovh
py-certbot-dns-route53
py-certbot-nginx

**Comment by bmw** [comment]
I don't think so. I'm honestly sympathetic to this request, however, I think MidnightBSD is niche enough that it doesn't really make sense for us to prioritize this work. Sorry.
