### ISSUE TITLE
Incorrect plugin package name for Devuan distro

### ISSUE THREAD

**Issue by osirisinferi** [certbot/website#786]
Currently, the instruction generator says to install e.g. `certbot-nginx` for the Devuan distro. However, these packages do not exist and this will cause confusion such as [in this thread on the Community](https://community.letsencrypt.org/t/certbot-nginx-plug-in-fails-to-install-on-devuan/195073).

If you check https://pkginfo.devuan.org/cgi-bin/policy-query.html?c=package&q=*certbot*&x=submit it seems the packages are called `python3-certbot-XXX`.

I'm not familiar with Devuan and I don't know if the `certbot-XXX` packages once existed, but I think either upstream Devuan packagers should perhaps be informed that their `certbot-XXX` packages are missing or the instruction generate needs to be updated to use the `python3-certbot-XXX` package names.

**Comment by bmw** [comment]
Thanks for flagging this. I can't fix this myself anymore, but I've opened a ticket internally.

**Comment by bmw** [comment]
This has been fixed.
