### ISSUE TITLE
update install instructions to not install EOL `core` snap

### ISSUE THREAD

**Issue by XSpielinbox** [certbot/website#787]
The install instructions include the section "Ensure that your version of snapd is up to date", where it is written one shall execute `sudo snap install core; sudo snap refresh core`.

This is problematic for multiple reasons in my opinion:
1. `core` is out of standard support for almost 2 years now, as it based on Ubuntu 16.04 LTS. One does not recieve security updates for it unless one is using Extended Security Maintenance from Canonical.
2. `core` is not needed by certbot: As can be seen in the [source code](https://github.com/certbot/certbot/blob/master/snap/snapcraft.yaml), certbot uses `core20` and not `core`. When skipping this step and directly running `sudo snap install certbot` it also installs `core20` if not yet installed, but not `core`. Still certbot is fully functional.
3. It is extremely difficult to remove `core` after it has been installed. For historic reasons `core` is it's own kind of snap and in many circumstances one cannot uninstall it again, after it has been installed, leaving an almost unmanageable security risk.
4. `snapd` is not `core`. To ensure, `snapd` is up to date, one should simply run `sudo snap refresh` to refresh all snaps (what I would find way more advisable also for the base snaps anyway) or `sudo snap refresh snapd` if one really only wants to touch `snapd`.

I therefore would be very thankful if the instructions could be changed to only include a `sudo snap refresh` or if one really wants the extra maintenance burden to keep the instructions up to date and be extra explicit `sudo snap install core20; sudo snap refresh snapd`.

**Comment by alexzorin** [comment]
Originally we added `sudo snap install core` (see https://github.com/certbot/certbot/issues/8280 and https://github.com/certbot/website/pull/650). because it was the only command that reliably worked on every platform.

 >snapd is not core. To ensure, snapd is up to date, one should simply run sudo snap refresh to refresh all snaps (what I would find way more advisable also for the base snaps anyway) or sudo snap refresh snapd if one really only wants to touch snapd.

I pulled the `snap install core` advice directly from https://snapcraft.io/docs/installing-snap-on-debian, and it's still there. 

If Canonical want to update their advice we will follow it, but I am otherwise quite hesitant to jump directly to `snap refresh snapd` without a lot of testing. [We considered and rejected installing/refreshing the `snapd` snap on previous occassions.](https://github.com/certbot/certbot/issues/8280#issuecomment-698192437)

**Comment by alexzorin** [comment]
Debian 10 is still affected and is our 3rd most popular distribution with something like half a million users. I'd be inclined to remove these instructions once it hits its first EOL on 2022-09-10, but probably not until then.

Others on the team may disagree so I'll leave this issue in triage.

**Comment by alexzorin** [comment]
Well, that date is in the past. Silly me. So I am officially in favor of removing it and doing `snap install snapd`. I'm just going to check CentOS 7 and Ubuntu 18.04 and I'll get this change requested. Thanks!

**Comment by alexzorin** [comment]
I'm going to ask to see the snap installation growth for Debian 10 in a weeks time. If it's not growing much, we'll make the change.

**Comment by alexzorin** [comment]
OK, the number of Debian 10 installations are shrinking. We are going to get this removed.

**Comment by alexzorin** [comment]
The `snap install core` instruction is now gone.
