### ISSUE TITLE
Hosting provider page - incorrect Github links

### ISSUE THREAD

**Issue by KarlAustin** [certbot/website#789]
Page: https://certbot.eff.org/hosting_providers

The links for submitting a pull request and tips for editing go to an incorrect repo.  They are set as /website not /certbot/website

![image](https://user-images.githubusercontent.com/5338970/232726151-fb9313f4-25d4-410a-9d19-41840ab50fa3.png)

**Comment by bmw** [comment]
Thanks for taking the time to report this. I don't have access to the code myself anymore, but I've flagged this for the team at EFF who does.

**Comment by zoracon** [comment]
This appears to be fixed. 👍🏾
