### ISSUE TITLE
Windows "Test automatic renewal" instructions are missing a "-"

### ISSUE THREAD

**Issue by osirisinferi** [certbot/website#791]
Quite simple:

The part:

> For example, if your webserver is Apache 2.4, add the following to the certbot renew command:
> 
> $ -pre-hook “net stop Apache2.4” --post-hook “net start Apache2.4”

Is missing a `-` in the `--pre-hook` command: just a single dash at the front instead of the required two dashes.

Also, it would be nice if this part could use the webserver information to generate specific hooks instead of a generic example for Apache, even if "nginx" is selected as webserver.

**Comment by alexzorin** [comment]
If somebody with edit privileges reads this issue, please also action https://github.com/certbot/certbot/issues/8215 at the same time!

**Comment by ohemorange** [comment]
The latter change is more complicated, but the `--` is fixed. Going to close this, feel free to open a new PR if you want about the other thing.
