### ISSUE TITLE
Website Ubuntu Instructions Provide Wrong Removal Commands

### ISSUE THREAD

**Issue by machineghost** [certbot/website#798]
If you go to https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal you'll see these instructions:

>The exact command to do this depends on your OS, but common examples are sudo apt-get remove certbot, sudo dnf remove certbot, or sudo yum remove certbot.

Notice that none of those command use Snap ... but in the very next instruction, you're going to tell people to install *with Snap*:

>sudo snap install --classic certbot

In summary, you tell people to install with Snap, and then when they come back months later to reinstall, you give them every removal command *except* the Snap one.

It would make much more sense for the Snap removal command to be the first recommended command, since anyone who has used Certbot before will have it installed that way.

Thus, I propose modifying that section of https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal to: 

>The exact command to do this depends on your OS, but common examples are `sudo snap remove  certbot`, sudo apt-get remove certbot, sudo dnf remove certbot, or sudo yum remove certbot.

**Comment by machineghost** [comment]
P.S. One other minor suggestion.  Step #5 offers this command:

    sudo ln -s /snap/bin/certbot /usr/bin/certbot

But if you've already done this before, you'll already have that file, and you'll get:

> ln: failed to create symbolic link '/usr/bin/certbot': File exists

It would probably be worth adding a sentence that at least mentions that fact, and also mentions that you can use the `-f` flag to replace the existing one (if you want to; you can also just leave the old one there).

I would propose the following addition to the end of step #5's text:

>**NOTE:** If you have used Certbot previously this file will already exist, and this command will fail.  In that case you can either leave the existing symbolic link there, or you can replace it by adding `-f` to the previous command, ie. `sudo ln -sf /snap/bin/certbot /usr/bin/certbot`.

**Comment by osirisinferi** [comment]
Question: the instruction generator assumes Certbot isn't already installed using snap. When Certbot is already installed using snap, why would they want to follow this instructions to begin with? It's not the **re**-install Certbot instruction generator.

Maybe that might need some clarification, I dunno 🤷‍♂️

**Comment by machineghost** [comment]
I saw no "how to update your cert" instructions on the site, so I just re-followed the initial instructions.

Perhaps a similar page focused on how to refresh certs would eliminate any possible confusion on this issue AND make it simpler for people to know how to update their certs?

**Comment by osirisinferi** [comment]
I think you're looking for the Certbot user guide: https://eff-certbot.readthedocs.io/en/stable/using.html

**Comment by machineghost** [comment]
That link does not appear to be present on https://certbot.eff.org/ (ie.
the first place anyone would look for it) ... perhaps it should be?

Jeremy

**Comment by osirisinferi** [comment]
> That link does not appear to be present on https://certbot.eff.org/ (ie. the first place anyone would look for it) ... perhaps it should be?

The user guide can be found on https://certbot.eff.org/pages/help (the "get help" link at the top of any page on https://certbot.eff.org/).

That said, I'm guessing it's fair to say that someone looking for the general Certbot user guide/documentation wouldn't necessarily search for that behind a "get help" button.

**Comment by machineghost** [comment]
As a user, when I look at https://certbot.eff.org/, the large "Get Certbot instructions" button is the first actionable item I see on the page.  Whether I'm doing this for the first time or the two hundredth, there's a pretty decent chance I'm going to click that button (not "get help" or anything else, because my goal is to get a cert, not help).

After that I wind up on a page like https://certbot.eff.org/instructions?ws=apache&os=ubuntufocal ... which suggests "`sudo apt-get remove certbot`, `sudo dnf remove certbot`, or `sudo yum remove certbot` ... but not `sudo snap remove  certbot` (ie. the correct command if I'm doing this time 2 through 200 ... and possibly the correct command even for time 1).

Either you can provide a user like the one I described with the proper instructions to uninstall what they installed last time ... not on some side help page, but along the path they'll naturally follow ... and all it will cost you is 25-character addition to existing text ... or you can not.

**Comment by ohemorange** [comment]
Most users do not have a need or reason to uninstall what they installed last time; the same snap installation will continue to function and update itself. Certbot handles certificate updates automatically and most users rely on that functionality, so there should be no need to uninstall either certbot or existing certs.
