### ISSUE TITLE
Certbot install link broken on certbot.eff.org/instructions

### ISSUE THREAD

**Issue by Klivess** [certbot/website#812]
The link (https://github.com/certbot/certbot/releases/latest/download/certbot-beta-installer-win_amd64_signed.exe) now leads to a 404 at (https://certbot.eff.org/instructions) for any software and system.

![image](https://github.com/user-attachments/assets/69343b5c-d48c-44f2-93ae-5cf490e43cee)

**Comment by wgreenberg** [comment]
Thanks for letting us know. As of 2.10.0, we stopped supporting the Windows installer, but you can still download the last built installer from the 2.9.0 release: https://github.com/certbot/certbot/releases/download/v2.9.0/certbot-beta-installer-win_amd64_signed.exe

**Comment by Grosso2001** [comment]
Gracias :)

**Comment by Klivess** [comment]
Thanks a lot!
