### ISSUE TITLE
Docs "edit on github" link 404s if there's no corresponding certbot/certbot github page.

### ISSUE THREAD

**Issue by vbrown608** [certbot/website#97]
Example: https://certbot.eff.org/docs/_modules/certbot/errors.html
(possibly everything under /docs/_modules/)

**Comment by vbrown608** [comment]
Also includes these two generated index pages:
https://certbot.eff.org/docs/genindex.html
https://certbot.eff.org/docs/py-modinde.html

**Comment by SwartzCr** [comment]
I guess it's because these get auto generated
we could check them in to the certbot/certbot repo but I'm not sure how we'd do on keeping them up to date.
Curious to hear what @bmw and @pde think

**Comment by mfb** [comment]
I'd /hope/ we could remove the github link for autogenerated pages, although I haven't tried yet. This bug also exists on readthedocs.org itself.

**Comment by vbrown608** [comment]
There's an open issue for this on the sphinx read the docs theme: https://github.com/snide/sphinx_rtd_theme/issues/252

**Comment by SwartzCr** [comment]
Most of these have now appeared again - also no one ever seems to have complained about this. i'm going to close this as resolved until we get a complaint? Feel free to re-open if you're more concerned about this
